services:
  - type: web
    name: encrypted-chat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FERNET_SECRET
        sync: false
      - key: PYTHON_VERSION   # 👈 NEW — forces Render to use Python 3.11.9
        value: 3.11.9
